### ISSUE TITLE
Add/reorganize unit tests for CClaimTrieCache/CClaimTrie

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#104]
We have decent coverage for integration testing the CClaimTrieCache together with CClaimTrie but we do  not have any unit tests for testing them separately. 

Especially for CClaimTrieCache, adding unit tests would help developers understand and debug the class. We'll have better confidence on the correctness of the code going forward.

### Acceptance Criteria
1.
2.
3.

### Definition of Done
- [ ]  Tested against acceptance criteria
- [ ] Tested against the assumptions of the user story
- [ ] The project builds without errors
- [ ] Unit tests are written and passing
- [ ] Tests on devices/browsers listed in the issue have passed
- [ ] QA performed & issues resolved
- [ ] Refactoring completed
- [ ] Any configuration or build changes documented
- [ ] Documentation updated
- [ ] Peer Code Review performed

**Comment by kaykurokawa** [comment]
Some tests were added here: https://github.com/lbryio/lbrycrd/pull/105 but could use more

**Comment by BrannonKing** [comment]
Waiting on #175 's proposed "separate PRs".

**Comment by BrannonKing** [comment]
Having combined the two claimtrie unit test files as part of my other story to reuse unit test framework, I now agree with @lbrynaut 's comment about that being a bad move; I should have moved the unit test framework into its own file instead. The one unit test file is just too large (now knocking on 4k lines); it needs to be split into a number of smaller files.

**Comment by bvbfan** [comment]
#316
