### ISSUE TITLE
Reimplement ClaimTrie as Patricia Trie

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbrycrd#106]
Our Claimtrie is inefficient because it must store lots of empty nodes when storing a long name. The solution is to use this: https://github.com/ethereum/wiki/wiki/Patricia-Tree

**Comment by shyba** [comment]
For the sake of having this documented, we should be mindful that there is a space efficiency optimization and a time efficiency one mixed in this change. If we are doing one or both is a pending discussion.
If we just change the trie without changing the how the hash is calculated we could solve the memory issue without a hardfork. While changing how the proofs are made to match the new data structure (skipping empty nodes) would require a hardfork.

**Comment by BrannonKing** [comment]
I was just doing some testing on node counts for this. With a million random strings (standard 60 characters), I end up with 25 million nodes in traditional trie. With the collapsed prefixes, I end up with 1.5 million nodes after a million insertions. That's a substantial difference! Next test: the qp trie. We can talk about where to check in my tests and what to name them next week.

**Comment by BrannonKing** [comment]
I'm attaching my experiments on this. I've concluded that the prefix trie is the right structure, and that it would drastically reduce our (present) memory usage. I've also decided that it won't be enough code to justify putting it in a separate library by itself.  I'll leave it here on the shelf and hope that we can get c++11 support in lbrycrd in the very near future.

[lbry_tries.zip](https://github.com/lbryio/lbrycrd/files/2394602/lbry_tries.zip)

**Comment by BrannonKing** [comment]
Last week I tested the code here with my same sample data: https://github.com/ytakano/radix_tree. It was slow and seemed to be a few nodes short of a full load. I didn't see a lot of other libraries that were easily accessible. I did not attempt to use Ethereum's trie code. It appeared complex, and I don't want to mix their code in with ours.
