### ISSUE TITLE
lbrycrdd allows broadcasting transactions containing invalid updates

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbrycrd#116]
`broadcast` will send transactions containing claim update outputs where the claim id is invalid. Invalid claim id sizes as well as incorrect or non-existent claim ids all get through. Attempting to broadcast such transactions should return a transaction rejected error.

**Comment by bvbfan** [comment]
Someone to work on?

**Comment by kauffj** [comment]
@jackrobison if you're able include the specific examples of transactions you're able to broadcast but should not be able to, it'd make this ticket stronger.

**Comment by bvbfan** [comment]
https://github.com/lbryio/lbrycrd/pull/192

**Comment by lbrynaut** [comment]
Just noting that #192 does not solve the issue posted.

**Comment by BrannonKing** [comment]
The `sendrawtransaction` method relays messages even if they aren't accepted into the local memory pool. This has been repaired in the upstream bitcoin, in mid 2016.

**Comment by BrannonKing** [comment]
This is fixed now that we have the upstream master merged.
