### ISSUE TITLE
Travis build for OSX seems to fail occasionally ? 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#120]
Getting these errors for the OSX Travis build: seems to be a new problem that started happening recently?  See : https://travis-ci.org/lbryio/lbrycrd/jobs/365289919 (also check current master)

==> Installing protobuf dependency: python@2
==> Downloading https://homebrew.bintray.com/bottles/python@2-2.7.14_3.el_capita
==> Pouring python@2-2.7.14_3.el_capitan.bottle.1.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3-2
Target /usr/local/bin/2to3-2
is a symlink belonging to python. You can unlink it:
  brew unlink python
To force the link and overwrite all conflicting files:
  brew link --overwrite python@2
To list all files that would be deleted:
  brew link --overwrite --dry-run python@2

**Comment by kaykurokawa** [comment]
The failure is consistently happening, not occasionally

**Comment by lbrynaut** [comment]
Resolved by #165
