### ISSUE TITLE
Update lbrycrd README to follow LBRY.io guidelines for README 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#121]

**Comment by tzarebczan** [comment]
Instructions should include how to run lbrycrd, how to create a config file and some basic commands

**Comment by kaykurokawa** [comment]
Initial work on this merged

**Comment by tzarebczan** [comment]
@kaykurokawa please add instructions on how to generate a lbry.conf, where it goes and sample rpc parameters for a typical configuration.

**Comment by kaykurokawa** [comment]
done
