### ISSUE TITLE
Transaction rejected,  absurdly high fees

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrycrd#127]
Due to the recent fee calculation for claim transactions, there's a new case we need to consider where a low bid is used along with a longer than usual claim name. The network rejects the transaction because the fee is much higher than the claim amount (not sure what this ratio is or how it's determined). 

I think we should be allowing these transactions as long as https://github.com/lbryio/lbry/issues/1045 is implemented and the user sees what their fees are. 

`{ "error": { "code": -32500, "data": [ " File \"site-packages\\twisted\\internet\\defer.py\", line 1299, in _inlineCallbacks", " ", " File \"site-packages\\lbrynet\\core\\Wallet.py\", line 567, in claim_name", " ", "exceptions.Exception: Claiming of name xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx failed: error: The transaction was rejected by network rules.(256: absurdly-high-fee)", "[0100000001cc9b534627af326895bc082dcc36a80bf1dd7e5abc9b6cdb256cd243204c25e5010000006b483045022100d94a973a0da7db747aafc5fd76aabfc571bf9b1146febecdf7d24cd9c86fd28202202cf3791ce8e95e01bba0604451a6fc8096e243db79e9f50648823103e7d8967a012103b5352083f9fd01c3afd1bad2d26896d424cfc81e8179d3e47c23fd52ccbbed43ffffffff02a086010000000000e8b54c4e7878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878784c7a080110011a740801122c080410011a0f6c6f6e6720636c61696d206e616d6522002a03746f6d32065075626c696338004a0052005a001a42080110011a309590c95fbf307f2a5c2701943a62ebca688b00aaec2d6a765e0c5fad77a54b1a4f14011d5d573a1bfc80c9499563d1b4220a696d6167652f6a7065676d7576a9144a81d0614f9b9b40c937ff23ae6b0d6f1e07d75688acc4dde004000000001976a91474e87a5e2061454e7db9192b12bbe0e35a6baa6488ac00000000]" ], "message": "Claiming of name xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx failed: error: The transaction was rejected by network rules.(256: absurdly-high-fee)\n[0100000001cc9b534627af326895bc082dcc36a80bf1dd7e5abc9b6cdb256cd243204c25e5010000006b483045022100d94a973a0da7db747aafc5fd76aabfc571bf9b1146febecdf7d24cd9c86fd28202202cf3791ce8e95e01bba0604451a6fc8096e243db79e9f50648823103e7d8967a012103b5352083f9fd01c3afd1bad2d26896d424cfc81e8179d3e47c23fd52ccbbed43ffffffff02a086010000000000e8b54c4e7878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878784c7a080110011a740801122c080410011a0f6c6f6e6720636c61696d206e616d6522002a03746f6d32065075626c696338004a0052005a001a42080110011a309590c95fbf307f2a5c2701943a62ebca688b00aaec2d6a765e0c5fad77a54b1a4f14011d5d573a1bfc80c9499563d1b4220a696d6167652f6a7065676d7576a9144a81d0614f9b9b40c937ff23ae6b0d6f1e07d75688acc4dde004000000001976a91474e87a5e2061454e7db9192b12bbe0e35a6baa6488ac00000000]" }, "id": null, "jsonrpc": "2.0" }`

**Comment by kaykurokawa** [comment]
I believe this is because people have not updated lbrycrd to master with the fee changes.
Also we didn't make a release so I will make that right now.

**Comment by tzarebczan** [comment]
@kaykurokawa isn't it just our lbryum-servers that need the updated lbrycrd? I believe @nikooo777 recently updated ours, so it should be working but I tried just now and seeing the same error for a long claim name. Will double check with Niko to see what version we are on

**Comment by nikooo777** [comment]
that was correct. Lbryum servers were not up to date with lbrycrd. I performed the upgrade

**Comment by tzarebczan** [comment]
Still occurring after the update of lbrycrd. 
Error message: Claiming of name xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx failed: error: The transaction was rejected by network rules.(256: absurdly-high-fee) [0100000001293cd7719793e2877206fdd841715a8e8294ed94e12c4e654bc4a65f6d0f9a7a0100000069463043021f7d1b545cb7676e60863eaa4be5ff762028f7ae0931647d8a9933c2302296c302201c4c0c1effd37e52138b2382edbcffe4e16c805573ca6922559c0c3e37f89dee0121035f1047fee37355cd7d27d0364a31b454c22afa26d673dbecc8528c73db2b800dffffffff021027000000000000fd6c01b54c4c787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878784dff00080110011af801080112a101080410011a3d78787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878224c787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878787878782a0032044e6f6e6538004a0052005a001a50080110011a30532554ab17c0d5fa9f7fc9f9fd26630f821aff5ff4f6bb3499cd7ab394c1e2fb4cd3b4226a6e0fa3defabc3514f17d7622186170706c69636174696f6e2f782d6d73646f776e6c6f61646d7576a9141f8056337420fd16d711decddf6b966e6617a20288ac54ceb009000000001976a914b3fe210dad8d2414e9e0e56bc0f850f69c901e4988ac00000000]

**Comment by kaykurokawa** [comment]
For the lbrycrd running on lbryum servers, 
is there a configuration (either in the configuraiton file or command line) that sets "maxtxfee" ?

**Comment by nikooo777** [comment]
i just checked, negative on that. nothing set for that variable

**Comment by alyssaoc** [comment]
@tzarebczan Is this still happen/an issue?

**Comment by nikooo777** [comment]
haven't seen it anymore on my side.

**Comment by tzarebczan** [comment]
Looks like it's not happening anymore with the above examples. Did a quick scan of loggly also, looks good in the past month. Closing...
