### ISSUE TITLE
Clean up compiler warnings

### ISSUE THREAD

**Issue by shyba** [lbryio/lbrycrd#129]
During compilation I'm getting a lot of warnings and most of them aren't relevant. We should at some point clean them up so its easier to read.
Another idea was to add a linter, but I'm undecided on which one, so I will leave that open and let us start by cleaning the noise instead.

**Comment by BrannonKing** [comment]
Waiting on #174

**Comment by BrannonKing** [comment]
I feel like this should be the standard:
`-Wall -Wextra -Wno-implicit-fallthrough -Wno-unused-parameter`
Right now, that much works on the post-merged code.
