### ISSUE TITLE
Include last block hash on claimtrie RPC results

### ISSUE THREAD

**Issue by shyba** [lbryio/lbrycrd#130]
Both lbryumx and lbryum/lbrynet could benefit from knowing which block hash the response came from, so it can check if that matches the current database state. It should also make it easier to check if the blockchain tip changed during large queries.

Use cases for other projects getting this information:
* lbrynet/lbryum asks for claims in a name. That currently doesn't accept a block hash parameter neither returns the block hash itself and it's not yet possible to use a block hash to query a previous claimtrie state at arbitrary blocks, specially if the hash is from a fork. So, the easiest way to ensure consistency is to return the hash and compare with the database tip.
* lbryum-server/lbryumx is querying and the block tip changes right before the query or during a large query. It's useful to know that as this wont match the database tip and could require information that's not in fetched yet or to discard previous results to get consistency.
* worst case: lbrynet specifies a block hash for URI resolutions, we get a proof for that tip but all the other info comes from the current tip. It's hard to know when that happened and having mixed information can easily bring weird results such as a proof on a block tip that has no claim information (the claim got abandoned on the next blocks).

Modifications on lbrycrd code:
* if a claimtrie RPC command accepts an optional block hash parameter, include it in the response if no hash is given as parameter.
* if a claimtrie RPC command doesn't accept block hash paramter, include it in the response so the client knows the tip at which the query occurred.

**Comment by kaykurokawa** [comment]
This is a related issue https://github.com/lbryio/lbrycrd/issues/44, and PR: https://github.com/lbryio/lbrycrd/pull/189

The code required to implement minconf is nearly identical to the code required to implement blockhash as an argument. And blockhash can be used to implement minconf (look up the block hash on the particular height), so I believe #189 should be modified to use blockhash.

**Comment by BrannonKing** [comment]
Thanks for pointing out the connection. I concur on using blockhash for #44. I will make that change and resubmit #189. I will also add this (return the block hash) into #189 as I think it would be trivial. My current plan is to get a working implementation on #107 first, though, unless somebody wants to argue for this as a higher priority.

**Comment by BrannonKing** [comment]
We've adjusted #44 to make the RPC methods take an optional blockhash. It will return an error if the blockhash cannot be accommodated. Is that sufficient to achieve this? Or is there value in returning a blockhash field for the case when you want the current tip? (Which would be a rare situation when the API is used by a higher-level entity.)

**Comment by kaykurokawa** [comment]
@shyba confirmed that it #44 will fix this
