### ISSUE TITLE
Larger than normal fees on some tipbot transactions

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrycrd#132]
Larger fee: https://explorer.lbry.io/tx/6283e3a0b6bc16ac22c3446ee42a09d3ae7496551f86c037d333bc973c0b9e50 - it's for a Discord tipbot withdrawal. 

I've noticed higher fees on these sometimes, but others they are normal like: https://explorer.lbry.io/tx/4acbfd68cedd791c5d08eb63e344fba9d6ca55dc899dc7404e29b09a4aa70ca1

getinfo:
```
{
  "version": 129900,
  "protocolversion": 70013,
  "walletversion": 60000,
  "balance": 65165.76858360,
  "blocks": 363598,
  "timeoffset": 0,
  "connections": 8,
  "proxy": "",
  "difficulty": 10248737.89916201,
  "testnet": false,
  "keypoololdest": 1524849129,
  "keypoolsize": 101,
  "paytxfee": 0.00000000,
  "relayfee": 0.00001000,
  "errors": "This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"
```

**Comment by BrannonKing** [comment]
Possibly associated with: https://github.com/bitcoin/bitcoin/commit/0f402b9263b0579b29aa0f841fc64ad58d3efba6

**Comment by BrannonKing** [comment]
I'm not planning to do anything about this at this point in time. The fee estimator relies on other data flowing through the mempool. The whole thing is painfully complex, supporting multiple "horizons" of estimates. I can't justify the time to work through it. A fresh node with no mempool history could wildly fluctuate on its fee calculation, having not enough data to make a good average. 

Also, there is a minimal fee for the name: for new claim name ops specifically, there is a minimum fee of 200k sats per byte in the name.
