### ISSUE TITLE
Something goes wrong when saving claimtrie nodes to disk and loading it  

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#133]
Discovered in https://github.com/lbryio/lbrycrd/pull/110 

When loading in claimtrie nodes using function InsertFromDisk() https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L1072 , we discovered that for some reason the "name" variable contains an extra bogus character at the end.

However, I suspect that there is not always a bogus character attached to the "name" variable, thus this function will completely fail. 

I've tested the serialization classes to see if there is any problem loading/saving string classes and there is no problem, so its likely a problem originating from when we save nodes, particularly when the function markNodeDirty() gets called https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L828 which marks nodes to be saved on disk.

**Comment by bvbfan** [comment]
This *probably* should be fixed when merging new code.

**Comment by BrannonKing** [comment]
I'm closing this as unreproducible. The serialization code has been updated with the upstream merge. Also, the code for loading the trie will be different with the new memory improvements.
