### ISSUE TITLE
Disk related functions should be seperated out from ClaimTrie class into its own class

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#136]
All disk read/write functions done through the CDBWrapper class in ClaimTrie should be separated out onto its own file/class. This should improve readability as it should be much clearer what is being saved and how. We should also write unit tests for the separated out disk read/write class.

**Comment by bvbfan** [comment]
I will try to this task. You mean CDBWrapper (reads from disk) as well as CDBBatch (write to disk) in related class, right?

**Comment by kaykurokawa** [comment]
Yes basically anything that has to do with CClaimTrie.db

**Comment by bvbfan** [comment]
I found that architecture is not good enough to me. Did you accept more agressive refactor? Why, CClaimTrieCache should have all *dirty* nodes and CClaimTrie should search in, when it's not found, then query CClaimTrieDb (new separed class) so CClaimTrie became a interface between cache and db. This will result in remove of all dirtyQueueXXX and related functions from CClaimTrie. Is this acceptable to you?

**Comment by bvbfan** [comment]
https://github.com/lbryio/lbrycrd/pull/140
It's simple, i can make more *aggressive* refactor if still needs

**Comment by alyssaoc** [comment]
closing for #175
