### ISSUE TITLE
nCurrentHeight in ClaimTrie and ClaimTrieCache needs to be renamed

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#138]
nCurrentHeight, a member variable in ClaimTrie and ClaimTrieCache, is not the actual current height. 
It is the current height + 1 (i.e, if there is a total of two blocks including the genesis, nCurrentHeight is 2 where as the standard definition of current height would be 1) , or perhaps it can be called as the current height "to be worked on". 

nNextHeight might be a better name.

**Comment by kauffj** [comment]
@kaykurokawa add comment until refactor happens?

**Comment by bvbfan** [comment]
I can take it on my refactor branch, it's sound good?

**Comment by bvbfan** [comment]
It is nNextHeight in my local branch i'll made pull request.

**Comment by alyssaoc** [comment]
@bvbfan Can this issue be closed?

**Comment by bvbfan** [comment]
Still not, i've plan to do RR, but i don't want to bother normalization work.
