### ISSUE TITLE
Consider tuning ancestor/descendant size limit for our use case

### ISSUE THREAD

**Issue by shyba** [lbryio/lbrycrd#139]
While publishing lots of videos, @nikooo777  got:
Transaction rejected: 64: too-long-mempool-chain

Which comes from: https://github.com/lbryio/lbrycrd/blob/4ff143387ef98ffb7e57b3b07f11714589f6d85c/src/main.cpp#L1249

Which is affected by:
-limitancestorcount
-limitancestorsize
-limitdescendantcount
-limitdescendantsize

At the time it last happened, this was the mempool info output:
```bash
[lbry@lbryum8:~] $ ./lbrycrd/lbrycrd-cli getmempoolinfo
{
 "size": 82,
 "bytes": 84031,
 "usage": 159920,
 "maxmempool": 300000000,
 "mempoolminfee": 0.00000000
}
```

This issue opens a discussion on what would be the best move on this subject and if there are other solutions.

**Comment by shyba** [comment]
Solution I would consider: What if the node being used for large scale publishes raises this limit? Will the mempool get rejected all the time? Would it solve or trigger another issue?

**Comment by alyssaoc** [comment]
@shyba and @nikooo777  Is this still an issue? What is the impact/priority?

**Comment by alyssaoc** [comment]
closing per conversation with Niko and Victor
