### ISSUE TITLE
CClaimTrieCache should be renamed

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#145]
The naming of CClaimTrieCache in claimtrie.h/.cpp has caused a lot of confusion. 
It is not a Cache for CClaimTrie, it is a cache of pending changes to CClaimTrie upon block increment/decrement.

**Comment by kaykurokawa** [comment]
CClaimTrieUpdateBuffer might be a good name

**Comment by bvbfan** [comment]
You can merge safety, it has only rename and separate.

**Comment by BrannonKing** [comment]
Now that the new one acts like a cache, we decided that renaming it was not necessary.
