### ISSUE TITLE
Should create function for claim processing code in main.cpp 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#151]
Claim processing code that goes in main.cpp's ConnectBlock() and DisconnectBlock() should be refactored into functions. 

https://github.com/lbryio/lbrycrd/blob/v0.12.2.0/src/main.cpp#L2588

https://github.com/lbryio/lbrycrd/blob/v0.12.2.0/src/main.cpp#L2160

This should remove code duplication in miner.cpp  : https://github.com/lbryio/lbrycrd/blob/v0.12.2.0/src/miner.cpp#L320

And also allow us to write unit tests  for transaction parsing on claim commands and achieve better seperation between Bitcoin Core code and claimtrie code.

**Comment by BrannonKing** [comment]
merged
