### ISSUE TITLE
making pool. how to lbry hash verification?

### ISSUE THREAD

**Issue by trustfarm-dev** [lbryio/lbrycrd#162]
Hi, I'm making LBRY pool.
I've adds lbry hashing module to NOMP node_multihashing module.
followings issue on NOMP.
https://github.com/zone117x/node-open-mining-portal/issues/611 

I want to check my ported hashing modules output is ok? could you check algorithm porting is good?
and what multiplier I use?

thanks

**Comment by kaykurokawa** [comment]
I would guess that you'd need to adjust the difficulty adjustment algorithm : https://github.com/lbryio/lbrycrd/blob/master/src/pow.cpp#L47

I'm closing this as it's not a lbrycrd issue. If you need further help contact me directly: kay@lbry.io 

Thanks.

**Comment by tzarebczan** [comment]
@trustfarm-dev check out https://github.com/lbryio/pool, should be helpful.

**Comment by ekxoiner** [comment]
Please help me how ti claim my LBRY? And withdrawal to market in coinomi,
this my ADDRESS in coinomi

bM2Yh7V2GN9aC4kH9eqaoUUDN4Fd3SDCGk

Rabu, 20 Juni 2018, Thomas Zarebczan <notifications@github.com> menulis:

**Comment by tzarebczan** [comment]
@ekxoiner looks like you are in the wrong place and not sure what you are asking.

**Comment by ekxoiner** [comment]
Hai,

Saya baru saja menandatangani petisi "Binance: Bitcoin Black (BCB) on
Binance" dan ingin tahu apakah Anda dapat membantu dengan menambahkan nama
Anda.

Tujuan kami adalah untuk mencapai 1.500 tanda tangan dan kami membutuhkan
dukungan lebih banyak. Anda dapat membaca lebih banyak petisi dan
menandatanganinya di sini:

http://chng.it/QJdVBbLJn7

Terima kasih!
Wahyanto

**Comment by ekxoiner** [comment]
Hai,

Saya baru saja menandatangani petisi "Presiden @Jokowi, Bantu Muslim Uighur
di Tiongkok." dan ingin tahu apakah Anda dapat membantu dengan menambahkan
nama Anda.

Tujuan kami adalah untuk mencapai 50.000 tanda tangan dan kami membutuhkan
dukungan lebih banyak. Anda dapat membaca lebih banyak petisi dan
menandatanganinya di sini:

http://chng.it/qYKHkGdH9b

Terima kasih!
Wahyanto
