### ISSUE TITLE
git clone --depth=1 and git reset --hard; git push -f?

### ISSUE THREAD

**Issue by teran-mckinney** [lbryio/lbrycrd#2]
Hi,

This is a huge repository coming from Bitcoin initially. Are you planning to cherry pick things from upstream Bitcoin/BitcoinXT? If so, does having the commit history help?

I wonder if it would be worth it to reset the repo to the state where you started modifying it for lbrycrd. Would really shrink it down, possibly with no side-effects (maybe something legally?).

This is very minor and nitpicky, but I'm also curious of a good reason not to, because it could be something I've not though of and should know.

Thanks,
Teran

**Comment by whitslack** [comment]
@teran-mckinney There's no reason to erase history from the repository on GitHub, and keeping the history allows automated merging from upstream. If you don't want to download the full history when checking out `lbryio/lbrycrd`, you can do a shallow clone.

**Comment by teran-mckinney** [comment]
That's fair, I think you're right.

Thanks!
