### ISSUE TITLE
Claim expiration time is set to 262974 blocks, or 456.55... days

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#20]
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.h#L285

Claim expiration time is set to 262974 blocks or 456.55... days. 

Should be set to 52416 blocks or 91 days, according to original design document. Will require hard fork and reindexing. 

We have roughly till the end of August to fix this issue in a simple way. Otherwise there needs to be exceptions made for early blocks.

**Comment by kaykurokawa** [comment]
Team discussion on 8/12 concluded that we will look to extend the expiration time. 365 days was tentatively suggested as a possible expiration time.

**Comment by kauffj** [comment]
I see no need to change this, and certainly not to reduce it.
