### ISSUE TITLE
Travis builds sometimes cannot complete due to missing style scripts

### ISSUE THREAD

**Issue by lbrynaut** [lbryio/lbrycrd#201]
Travis sometimes reports that it can't find the required clang formatting scripts.  This was seen originally on OS X (where it was arbitrarily disabled without investigating further for a fix) and it is now showing on GNU/Linux.

An example build failure shows as

```
./reproducible_build.sh: line 421: ./contrib/devtools/clang-format-diff.py: No such file or directory
+LINES_W_FORMAT_REQUIRED=0
```

An example log is here:

https://travis-ci.org/lbryio/lbrycrd/jobs/424021818

**Comment by BrannonKing** [comment]
I think this is fixed via #241. I'll reopen this if I see the error again.
