### ISSUE TITLE
Consider adding pendingEffectiveAmount data to claim information

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrycrd#203]
Currently, we have a data field called EffectiveAmount which shows the current claim bid, including any tips and supports. During a claim takeover bid, the effective amount of the newly bid claim is set to 0 until the takeover completes. If another user tries to take over the vanity URL, they will only be aware of the current vanity claim bid, and not the pending one which could be outbidding theirs. Optimally, we would show the current and any pending claim takeover bids.

**Comment by kaykurokawa** [comment]
Can confirm that this is indeed the case, can check via getclaimsforname for example (but also same case with getclaimbyid) 

```
{
  "nLastTakeoverHeight": 412837,
  "claims": [
    {
      "claimId": "5cbbfe31cd8fbaf442097981474bfa81bd068469",
      "txid": "d5b135291ea857ff73b7a4c9e97cffcd2a7934aa63d33409bc5c12710b286818",
      "n": 0,
      "nHeight": 412837,
      "nValidAtHeight": 412837,
      "nAmount": 10,
      "value": "",
      "nEffectiveAmount": 10,
      "supports": [
      ]
    }, 
    {
      "claimId": "56257f567cc64505e145b56d773004f79a53c576",
      "txid": "ca72c26365364093163308b5b983504261ab602f360e3487b4287c2a7b1aca5b",
      "n": 1,
      "nHeight": 591604,
      "nValidAtHeight": 595636,
      "nAmount": 2000000000,
      "value": "\u0000\u0000",
      "nEffectiveAmount": 0,
      "supports": [
        {
          "txid": "63aa07fc65c831f88ba1fb4f8f94353e93e5117cbbf5c7ea8dfb2da659f4cc29",
          "n": 1,
          "nHeight": 591607,
          "nValidAtHeight": 595639,
          "nAmount": 1000000000
        }
      ]
    }
  ],
  "supports without claims": [
  ]
}

```

This happens because before claim's effective amount is only calculated in the claim trie. When claims are not activated yet, there are not placed in the claim trie, they are placed in a queue. In the queue, effective amount does not matter because it is only important for calculating the winning claim of the name and claims in the queue cannot win.

**Comment by bvbfan** [comment]
Claims have in itself nEffectiveAmount that is calculated despite current height, which is actual reason to not show it. I think we should serialize nEffectiveAmount from CClaimValue @BrannonKing told that on other issue.

**Comment by bvbfan** [comment]
#232

**Comment by tzarebczan** [comment]
@bvbfan does your fix also take into account supports? I also noticed supports don't show until the takeover occurs.

**Comment by bvbfan** [comment]
@tzarebczan it should.

**Comment by BrannonKing** [comment]
Updated requirement: we need to expose queued supports in the RPC methods. These should probably go in the "supports without claims" section.

**Comment by BrannonKing** [comment]
Merged via https://github.com/lbryio/lbrycrd/pull/303
