### ISSUE TITLE
lbrycrdd should have a logroll if its printing console output to logs.

### ISSUE THREAD

**Issue by Leopere** [lbryio/lbrycrd#211]
Since it prints every line about every bit of indexing that it does it should be able to roll the log file a bit so that you don't end up with a full blockchain sized log file.

**Comment by BrannonKing** [comment]
I think we should also audit what is currently being written to debug.log.

**Comment by kaykurokawa** [comment]
I removed the biggest culprit here, this would dump about 200mb worth of stuff on every claimtrie flush:
https://github.com/lbryio/lbrycrd/commit/7eca4f00a7a6d24d8386dab733e136940ef457f2

Did an audit of the other logs, they don't cause too much of a problem in terms of the volume of logs. 

These definitely should be removed, as they serve no useful purpose other than debugging for devs: 

https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L608
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L614
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L1598
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L1629
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L1945 
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L2111
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L2384

Below could be removed they do show some useful claim information (for example, a new claim gets created), but not sure if that's something that should go into the logs.

https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L58
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L65
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L1592
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L1611
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L1697
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L2001
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L2020
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L2098
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L2105
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L2163
https://github.com/lbryio/lbrycrd/blob/master/src/claimtrie.cpp#L2215

**Comment by BrannonKing** [comment]
Your assessment looks good. I think we should also remove those 7 you suggest. I think we should keep a log entry for each user addition/subtraction, so I think most on the bottom list should stay. It looks like we may be logging added claims twice, though -- both add and insert?

**Comment by bvbfan** [comment]
I'm worried of this line too -> https://github.com/lbryio/lbrycrd/pull/159/commits/80940714a1015dd8dcc22de8d53ae99bff65328f#diff-1f647c4b5527c3d3e86cfb735380b479R60

**Comment by BrannonKing** [comment]
@bvbfan , I do have that line removed in my normalization work.

**Comment by kaykurokawa** [comment]
The fixes in this release https://github.com/lbryio/lbrycrd/releases/tag/v0.12.2.3 will remove much of the unnecessary logging. lbrycrdd has a function that will automatically shrink large log files upon startup, so we will not implement a log roll/rotation. 

Users that want a log roll/rotation should implement their own (the automatic shrinking of log files can be disabled through option -shrinkdebugfile )

**Comment by BrannonKing** [comment]
I propose that we start a new file with each run, and that we backup the old file. Hence, I should always have this run and the previous one available. That's not quite a "roll" of logs, in that it won't fix the maximum size while the daemon is running, but I think it would help.

**Comment by gahag** [comment]
@BrannonKing can I work on this to implement what you described in your last comment?

**Comment by BrannonKing** [comment]
@gahag , yes you can work on this.

**Comment by gahag** [comment]
I've explored the code, and I'm thinking of implementing in `BCLog::Logger::OpenDebugLog`. The code would move the debug file if it exists to a `.old` file. This way, there would be one file for each execution of the entire application. Another option would be to implement such code in the default constructor for `BCLog::Logger`. What do you guys think?

**Comment by BrannonKing** [comment]
Look at the top of `AppInitMain()`; the "shrink" code there would also need to change.

**Comment by gahag** [comment]
Sure. What are we expecting to be the new behavior of the -shrinkdebugfile flag? Should it be removed, or should it shrink the old log file?

**Comment by BrannonKing** [comment]
I think the flag should be removed.

**Comment by Leopere** [comment]
This looks like it should've been closed by #344 I don't have time to really validate this functionality but if people see this PR didn't hit the notes that this thread evolved to hit then please feel free to re-open it.
