### ISSUE TITLE
Add examples to api documentation 

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrycrd#219]
To add onto https://github.com/lbryio/lbrycrd/pull/187 and fulfill https://github.com/lbryio/lbry.tech/issues/139, can we generate example calls for each command?

**Comment by kaykurokawa** [comment]
Noting here that there are example calls for commands but it is not being  parsed properly

**Comment by BrannonKing** [comment]
@tzarebczan ,  it's not clear (looking at the parent bug) whether you want command-line examples for this or JSON RPC examples. 

Other thoughts: the current "example" sections in the API docs came from the embedded help text in the lbrycrd RPC methods. They are for the command line tool, and they are not consistent in their formatting or in their inclusion on every RPC method. Most of the RPC methods come from pre-existing bitcoin code. I'm hesitant to change that code as it complicates our merge with upstream changes.

**Comment by kauffj** [comment]
Providing examples of how to run the commands via `cURL` or by directly running the CLI tool both make sense.

If I had to pick one, I'd probably say `cURL`, but this is not a particularly reasoned opinion. Ideally, we could just provide both or even more versions (see [Stripe API](https://stripe.com/docs/api) for an example of how this is done well). 

When I looked at the existing docs, it looked like it frequently contained both. Would it be feasible to parse to a structure like this?

```
    {
        "name": "getblock",
        "namespace": "Blockchain",
        "description": "If verbose is false, returns a string that is serialized, hex-encoded data for block 'hash'. If verbose is true, returns an Object with information about block <hash>.",
        "examples": {
            "cli": "lbrycrd-cli getblock \"00000000c937983704a73af28acdec37b049d214adbda81d7e2a3dd146f6ed09\",
            "curl": "curl --user myusername --data-binary '{\"jsonrpc\": \"1.0\", \"id\":\"curltest\", \"method\": \"getblock\", \"params\": [\"00000000c937983704a73af28acdec37b049d214adbda81d7e2a3dd146f6ed09\"] }' -H 'content-type: text/plain;' http://127.0.0.1:9245/"
        },
        "arguments": [
            {
                "name": "hash",
                "type": "string",
                "description": "The block hash",
                "is_required": true
            },
            {
                "name": "verbose",
                "type": "boolean",
                "description": "true for a json object, false for the hex encoded data",
                "is_required": false
            }
        ],
        "returns": "{\n  \"hash\" : \"hash\",     (string) the block hash (same as provided)\n  \"confirmations\" : n,   (numeric) The number of confirmations, or -1 if the block is not on the main chain\n  \"size\" : n,            (numeric) The block size\n  \"height\" : n,          (numeric) The block height or index\n  \"version\" : n,         (numeric) The block version\n  \"versionHex\" : \"00000000\", (string) The block version formatted in hexadecimal\n  \"merkleroot\" : \"xxxx\", (string) The merkle root\n  \"nameclaimroot\" : \"xxxx\",  (string) The hash of the root of the name claim trie\n  \"tx\" : [               (array of string) The transaction ids\n     \"transactionid\"     (string) The transaction id\n     ,...\n  ],\n  \"time\" : ttt,          (numeric) The block time in seconds since epoch (Jan 1 1970 GMT)\n  \"mediantime\" : ttt,    (numeric) The median block time in seconds since epoch (Jan 1 1970 GMT)\n  \"nonce\" : n,           (numeric) The nonce\n  \"bits\" : \"1d00ffff\", (string) The bits\n  \"difficulty\" : x.xxx,  (numeric) The difficulty\n  \"chainwork\" : \"xxxx\",  (string) Expected number of hashes required to produce the chain up to this block (in hex)\n  \"previousblockhash\" : \"hash\",  (string) The hash of the previous block\n  \"nextblockhash\" : \"hash\"       (string) The hash of the next block\n}\n\nResult (for verbose=false):\n\"data\"             (string) A string that is serialized, hex-encoded data for block 'hash'."
    },
```

**Comment by kauffj** [comment]
@NetOperatorWibby nothing for you here yet I think, but tagging you so you can follow this ticket.

**Comment by tzarebczan** [comment]
@BrannonKing - the SDK team went ahead with the below output format for examples. I think LBRYcrd should be able to do something similar. Lex's plan is to execute these and grab outputs interactively via unit tests. 
https://gist.github.com/tzarebczan/1af2e79ba365a006d1b1f0079a3cb03c
https://github.com/lbryio/lbry/pull/1790

**Comment by BrannonKing** [comment]
I fixed the generator to include an examples field. It will populate it if the existing RPC had examples specified in its CLI help. I've checked in the new generator and the new api_v1.json file, but I have not gone through and added example sections to our claimtrie calls.

**Comment by BrannonKing** [comment]
@NetOperatorWibby , what do I need to do to close this ticket?

**Comment by tzarebczan** [comment]
@BrannonKing lbry.tech reads the json from here:  https://github.com/lbryio/lbrycrd/blob/add_api_docs_scripts/contrib/devtools/generated/api_v1.json

(https://github.com/lbryio/lbry.tech/blob/b6b274aa321f44cae057dadae300650cb082cfa9/app/components/edit-link.js)

Sounds like this link may need to be updated?

**Comment by NetOperatorWibby** [comment]
@BrannonKing You may be all set. I'll test it in tech first.

**Comment by NetOperatorWibby** [comment]
So, looks like JSDelivr has a cached version of the api json file so I had to email them to get it purged. No idea how long that's gonna take. Until they finish their purge tool, we'll have to keep emailing them with purge requests.

Another options is to version the compiled JSON file inside the `generated` folder.

**Comment by NetOperatorWibby** [comment]
Something weird is happening. Just realized I'm seeing the examples rendered inside of the description.

```
Sign a message with the private key of an address
Examples:
Unlock the wallet for 30 seconds
> lbrycrd-cli walletpassphrase "mypassphrase" 30

Create the signature
> lbrycrd-cli signmessage "1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XZ" "my message"

Verify the signature
> lbrycrd-cli verifymessage "1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XZ" "signature" "my message"

As json rpc
> curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "signmessage", "params": ["1D1ZrZNe3JUo7ZycKEYQQiQAWd9y54F4XZ", "my message"] }' -H 'content-type: text/plain;' http://127.0.0.1:9245/
```

**Comment by BrannonKing** [comment]
How do I version it? When I pull up https://github.com/lbryio/lbrycrd/blob/master/contrib/devtools/generated/api_v1.json I see that "Unlock the wallet" is correct.

**Comment by NetOperatorWibby** [comment]
By "version", I was thinking of doing something like `/generated/0.1.0/api.json`. However, I don't think that is necessary at this time since I _am_ seeing `examples`, they are merged with `description` for some reason.

**Comment by BrannonKing** [comment]
They were merged with description before I changed it a month ago. You're seeing an old version of the api_v1.json file.

**Comment by NetOperatorWibby** [comment]
https://cdn.jsdelivr.net/gh/lbryio/lbrycrd@master/contrib/devtools/generated/api_v1.json is still showing examples inside the description.

My email got a response from JSDelivr and I ran the curl command to purge twice. Still no change in the link above though. Maybe we just have to wait. I'll come back to this tomorrow.

**Comment by BrannonKing** [comment]
I have no idea how to update jsdelivr.net or why you might be pulling resources from there. I don't see why that would keep this issue open.

**Comment by kauffj** [comment]
This seems like it's in @NetOperatorWibby's court at this point.

**Comment by NetOperatorWibby** [comment]
Could the examples match what the SDK API file is doing? https://github.com/lbryio/lbry/blob/master/docs/api.json#L49-L57

```json
"examples": [
  {
    "title": "Get a file",
    "curl": "curl -d'{\"method\": \"get\", \"params\": {\"uri\": \"astream#e3f3e8a3307bcbb15fdaf97bb82340a3a86cf806\"}}' http://localhost:5279/",
    "lbrynet": "lbrynet get astream#e3f3e8a3307bcbb15fdaf97bb82340a3a86cf806",
    "python": "requests.post(\"http://localhost:5279\", json={\"method\": \"get\", \"params\": {\"uri\": \"astream#e3f3e8a3307bcbb15fdaf97bb82340a3a86cf806\"}}).json()",
    "output": "{\n  \"jsonrpc\": \"2.0\",\n  \"result\": {\n    \"blobs_completed\": 1,\n    \"blobs_in_stream\": 1,\n    \"blobs_remaining\": 0,\n    \"channel_claim_id\": \"cc242d221f78975c8011132882ee445b7d9b85cf\",\n    \"channel_name\": \"@channel\",\n    \"claim_id\": \"e3f3e8a3307bcbb15fdaf97bb82340a3a86cf806\",\n    \"claim_name\": \"astream\",\n    \"completed\": false,\n    \"download_directory\": \"/tmp/tmprlkz78lb\",\n    \"download_path\": \"/tmp/tmprlkz78lb/tmpit97x87b\",\n    \"file_name\": \"tmpit97x87b\",\n    \"key\": \"40d70a655061b7981b6d36a84d985fdc\",\n    \"metadata\": {\n      \"source\": {\n        \"hash\": \"b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9\",\n        \"media_type\": \"application/octet-stream\",\n        \"name\": \"tmpit97x87b\",\n        \"sd_hash\": \"a2d66638a51b1621538a92fe3fc4f7a34926dc415652d107b89e28d0bd962074b5bb758adfb3de55053f5cd4dfd97cc7\",\n        \"size\": \"11\"\n      }\n    },\n    \"mime_type\": \"application/octet-stream\",\n    \"nout\": 0,\n    \"outpoint\": \"eb2ff25e7588ea9bc5adeaf80ea66bff8770b5c983754e305b68e5b4199db898:0\",\n    \"points_paid\": 0.0,\n    \"protobuf\": \"01cf859b7d5b44ee82281311805c97781f222d24cce145c0ad7c3c76cd83b5f8044d097413f4198e39a8b4d8012e4055de83212fb94c12834f444142c49a9f46a786b31236b79c7612bdfccae897ef372792b9894e0a7f0a7d0a20b94d27b9934d3e08a52e52d7da7dabfac484efe37a5380ee9088f7ace2efcde9120b746d706974393778383762180b22186170706c69636174696f6e2f6f637465742d73747265616d3230a2d66638a51b1621538a92fe3fc4f7a34926dc415652d107b89e28d0bd962074b5bb758adfb3de55053f5cd4dfd97cc7\",\n    \"sd_hash\": \"a2d66638a51b1621538a92fe3fc4f7a34926dc415652d107b89e28d0bd962074b5bb758adfb3de55053f5cd4dfd97cc7\",\n    \"status\": \"running\",\n    \"stopped\": false,\n    \"stream_hash\": \"5bb823532eb1994bbb6c4a7ac44713249768f6e329e6e58a2c1e128ef9a029f850c30757909d0f961f7143a3b7ea439f\",\n    \"stream_name\": \"tmpit97x87b\",\n    \"suggested_file_name\": \"tmpit97x87b\",\n    \"total_bytes\": 16,\n    \"total_bytes_lower_bound\": 0,\n    \"tx\": null,\n    \"txid\": \"eb2ff25e7588ea9bc5adeaf80ea66bff8770b5c983754e305b68e5b4199db898\",\n    \"written_bytes\": 11\n  }\n}"
  }
]
```

**Comment by BrannonKing** [comment]
Done enough for now.
