### ISSUE TITLE
old hardfork tests spend too much time incrementing blocks

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lbrycrd#225]
[durations.txt](https://github.com/lbryio/lbrycrd/files/2496904/durations.txt)

See the attached file for unit test runtimes. Notice that the old hardfork tests take too long. We have a better mechanism to bring the hardfork block numbers in line with the number of blocks already mined in the unit test. I.e. from the normalization fork:
```cpp
    int currentHeight = chainActive.Height();
    const Consensus::Params& consensus = Params().GetConsensus();
    const_cast<Consensus::Params&>(consensus).nNormalizedNameForkHeight = currentHeight + 2;
```
Feel free to encapsulate this somehow.

### Acceptance Criteria
These tests have been sped up: hardfork_claim_test, hardfork_support_test, claimtriebranching_hardfork_disktest, claim_expiration_test

### Definition of Done
- [ ] Tested against acceptance criteria
- [ ] The project builds without errors
- [ ] Peer Code Review performed

**Comment by Techievena** [comment]
I want to work on this. Can you please help me with what needs to be done.

**Comment by BrannonKing** [comment]
done via cherry-pick
