### ISSUE TITLE
Repo Standards review

### ISSUE THREAD

**Issue by alyssaoc** [lbryio/lbrycrd#246]
## The Issue

In order to ensure the repo document standard is complete
as a team lead, 
I want to review and comment on the standard.

https://lbry.tech/resources/repository-standards

### Acceptance Criteria
1. Review the document 
2. Provide comments for discussion at team leads meeting

### Definition of Done
- [ ] Documentation updated

**Comment by BrannonKing** [comment]
For review at https://github.com/lbryio/lbrycrd/tree/depends_build_all

**Comment by BrannonKing** [comment]
in master now
