### ISSUE TITLE
Normalization Hardfork Computation Time

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#248]
I'm making some notes of the computation time required for the normalization hard fork, based on 950b9c1  #235 with patch https://github.com/lbryio/lbrycrd/pull/239 to test normalization hard fork on mainnet. Used my laptop: i5-6200U

To compute the block at normalization took about 1min45 seconds

To decrement this block takes about 30 seconds

Further, directly after passing the normalization height, restarting lbrycrdd takes about 8 minutes to pass the "Verifying block..." stage where it calls VerifyDB on main.cpp. Not sure why it would take so much longer here...

**Comment by BrannonKing** [comment]
It goes much faster if you compile it with optimizations enabled (CXXFLAGS=-O2 ...). I too had the same quandary, though. In looking at it just now I realized that the verification rolls back the past 100 blocks, and for each of them it rolls forward again. Doing that on the hard-fork transition block  would account for 2+ minutes of your verification time. However, I don't actually know how long it takes to read the transition block from the average disk. I'm using a supper fast nvme drive. It appears to read each block from the disk twice in the VerifyDB stuff.

**Comment by BrannonKing** [comment]
I'm closing this as "won't fix". It's not going to be a problem four hours after the hard fork is live. A lot of the time is in the block file seek time. (That's in the bitcoin core code.) The other time is in the trie construction, which we are fixing elsewhere (and won't have done before the hardfork hits.)
