### ISSUE TITLE
Normalization - Do we care about UCA versions

### ISSUE THREAD

**Issue by tiger5226** [lbryio/lbrycrd#255]
I just wanted to get this conversation out of slack and have documented for historical purposes. 

The unicode standards are always updated

<img width="649" alt="screen shot 2019-02-13 at 12 10 28 pm" src="https://user-images.githubusercontent.com/3402064/52730003-6058c980-2f88-11e9-97a3-8a7a1f6e256a.png">

LBRYcrd is use the ICU library for unicode support v57.1. This uses [UCA 8.0](http://www.unicode.org/Public/UCA/8.0.0/?C=M;O=A)

<img width="483" alt="screen shot 2019-02-13 at 12 43 27 am" src="https://user-images.githubusercontent.com/3402064/52729920-28518680-2f88-11e9-8a9d-dbe599e7bcb6.png">

Among our different services, there are 3 that standout in requiring unicode support also. 

LBRYNet - The base lbry uses [UCA 11.0](http://www.unicode.org/Public/UCA/11.0.0/?C=M;O=A)
Chainquery(MySQL) -  MySQL 8.0 users [UCA 9.0](http://www.unicode.org/Public/UCA/9.0.0/?C=M;O=A)
Lighthouse(ElasticSearch) - as of yet unknown

@lyoshenka Has already made the call that for Chainquery we will wait and see if there will be any issues between UCA 8.0 and UCA 9.0.

The list of migration issues are below

https://www.unicode.org/versions/Unicode9.0.0/#Migration
https://www.unicode.org/versions/Unicode10.0.0/#Migration
https://www.unicode.org/versions/Unicode11.0.0/#Migration

So the question is do we care? If not lets close this issue.

**Comment by BrannonKing** [comment]
After upstream merge, update Boost and ICU versions to match Unicode 11. In fact, can we ditch the lbrycrd_dependencies repo and use the "depends" folder instead?

**Comment by BrannonKing** [comment]
Upstream merge now includes ICU 62.

**Comment by lyoshenka** [comment]
doing some cleaning. reopen if this is still active.

**Comment by BrannonKing** [comment]
To clarify one thing: I'm planning to ship the next release with ICU 63.2 (which is still Unicode 11).
