### ISSUE TITLE
Update README to explain how to call server

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbrycrd#256]
The README explains how to start `lbrycrd` in server mode, but does not explain how to actually call the server or provide any sample calls. It would be good if it did.

**Comment by BrannonKing** [comment]
Do you think it should point to the CLI examples at lbry.tech ?

**Comment by tzarebczan** [comment]
I think a quick example (getinfo is a good one) with a link to the CLI would do.

**Comment by BrannonKing** [comment]
Note: do #246 when you do this one.

**Comment by kauffj** [comment]
link to https://lbry.tech/api/blockchain when this is done as well

**Comment by BrannonKing** [comment]
For review at https://github.com/lbryio/lbrycrd/tree/depends_build_all

**Comment by BrannonKing** [comment]
Merged.
