### ISSUE TITLE
Lbrycrd needs version scheme 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#26]
Need to figure out how versions will be set

https://github.com/lbryio/lbrycrd/blob/da53f17a28cb7609fdb421a82ac58f9a1649a30f/src/clientversion.h

**Comment by kaykurokawa** [comment]
Sensible proposal :
Major , Minor follows Bitcoin Core code (would be 12.0 currently) 
Client version build is used to track major lbry releases within the Core code base ( Increment from 0 up to 99). Current version could be 1 after soft fork at https://github.com/lbryio/lbrycrd/commit/874948ec59b7958f4212522f0b0b1f1b9cb224fb

**Comment by jobevers** [comment]
One nit - major.minor is currently `0.12` not `12.0`.

When you say client version, what do you mean?

Regarding tracking lbry releases - I don't understand what happens when it gets reset to 1; it seems that something else should get incremented when that happens.

**Comment by kaykurokawa** [comment]
You are right about the first point, to clarify , the Bitcoin Core version we are using is 0.12.0 (it is not really 0.12.99 , the 99 is a place holder indicating that it is not a release version) 

We use the first two numbers from the Bitcoin core version we are using, and than the last number gets incremented according to our releases. So we get 0.12.1 to 0.12.2 etc...

**Comment by jimmykiselak** [comment]
How is this going to handle future pulls from upstream?

**Comment by kaykurokawa** [comment]
For example , if bitcoin release is 0.12.0.1 our release is 0.12.0.X where X is some custom number we use. The last number in Bitcoin is for client builds which are usually not major changes, so we can use it to keep track of changes unique to Lbrycrd.

**Comment by kaykurokawa** [comment]
closed as https://github.com/lbryio/lbrycrd/pull/37
