### ISSUE TITLE
add brief Regtest description and link to setup 

### ISSUE THREAD

**Issue by binaryflesh** [lbryio/lbrycrd#261]
As a new user coming from the infosec side of things, 'regtest' is usually an alias to [fuzzing](https://en.wikipedia.org/wiki/Fuzzing). While writing a binding to the API, I was under impression to use testnet with my code and I thought '-regtest' was mainly an internal feature for developers on lbrycrd. Could there be mention of [ideal developer setup](https://lbry.tech/resources/regtest-setup) in the readme?

**Comment by tzarebczan** [comment]
Thanks for opening this issue @binaryflesh. Definitely something we need to mention here/how it works/where to find setup instructions.

**Comment by BrannonKing** [comment]
For review at https://github.com/lbryio/lbrycrd/tree/depends_build_all

**Comment by BrannonKing** [comment]
merged.
