### ISSUE TITLE
Investigate lbrycrd mode without storing claimtrie data in memory

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrycrd#264]
Some services, like exchanges and pools, will not care about claim trie data. Is it possible to have a mode or separate binary that's only for transactional data?

**Comment by BrannonKing** [comment]
I like this idea, but the root hash of the trie is included in the block. I can't think of a way to compute that without the data being there, and transferring it from somewhere else could be risky. The memory improvements are coming very soon and should buy us a lot of breathing room.

**Comment by BrannonKing** [comment]
Closing as a duplicate of #166
