### ISSUE TITLE
getClaimById needs to support a partial ID

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lbrycrd#268]
The getClaimById method needs to work with a front portion of the ID -- a shortened ID. If there are multiple matches it could return an error.

**Comment by tzarebczan** [comment]
The wallet server has implemented this, could be used as reference: https://github.com/lbryio/lbry/pull/2173

**Comment by BrannonKing** [comment]
Merged via https://github.com/lbryio/lbrycrd/pull/303
