### ISSUE TITLE
Byte size of value that can be assigned to name is not 20 kilobytes

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#27]
The current maximum value that can be assigned to a name is not 20 kilobytes as some has described. It is less than 8192 bytes. 

https://github.com/lbryio/lbrycrd/blob/master/src/nameclaim.h#L11

This will require a hard fork.

**Comment by abueide** [comment]
@kaykurokawa what would the effects of a hard fork be?

**Comment by kauffj** [comment]
I'm closing this, we're keeping it at 8KB for now.
