### ISSUE TITLE
new RPC method for querying with bid & sequence

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lbrycrd#270]
We need a new RPC method that supports more robust querying of the claim trie. This will eventually replace getclaimsforname, and it will need a corresponding "proof" RPC method that returns the merkle tree for the queried data. Requirements:

1. Allow querying on name, where it will return the winning bid for that claim name.
2. Allow querying on name and claim_id or partial claim_id.
3. Allow querying on name and sequence number (creation order).
4. Allow querying on name and bid number (according to current bid order).
5. Include an option to not return the value/metadata field.

Can it support a partial name if there is only one hit for that name? Maybe, but this isn't critical. Can it support no name or a partial name if the claim_id is given in full? Sure.

**Comment by lyoshenka** [comment]
sdk ended up taking this over
