### ISSUE TITLE
add optional metadata for supports

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lbrycrd#272]
This is prototyped in the metadata_for_supports branch. This sample implementation doesn't require a hard-fork in the code, but it probably needs one to ensure that enough people get the change. If we could instead get the metadata into the witness section of the block, we may be able to make this usable without a hard fork. See #273 

This is to enable options for advertisements and certifications and content reviews.

**Comment by tzarebczan** [comment]
Today supports cannot be updated, and supports can't support other supports. Any reason not to allow either or those, or it's just a matter of implementation? I could see use cases for both of those - updating a comment or review that's in the form of a support, and user's being able to support a comment / review. 

Any performance concerns as opposed to just doing the same with non winning claims that reference each other?  Seems about the same to me.

**Comment by BrannonKing** [comment]
@tzarebczan , we've had some discussion on adding what you suggest to supports. However, the current thinking is that if you want those features you should just use a claim. 

Supports can be updated; spend and reacquire one. The update command simply ensures that the spend and reacquire happen in the same block, but the consequence of it overlapping a block boundary would typically go unnoticed.
