### ISSUE TITLE
lbrycrdd crashes on after update new release package

### ISSUE THREAD

**Issue by osiztechnologies** [lbryio/lbrycrd#278]
We got below error message from terminal after update the v0.12.4.1 package.

lbrycrdd: main.cpp:2124: bool DisconnectBlock(const CBlock&, CValidationState&, const CBlockIndex*, CCoinsViewCache&, CClaimTrieCache&, bool*): Assertion `pindex->GetBlockHash() == trieCache.getBestBlock()' failed.
Aborted (core dumped)

we have tried -reindex. but not working properly.

Kindly guide how to resolve this issue.

**Comment by BrannonKing** [comment]
What version were you running before? You're using an official build or you compiled it yourself? Do you have anything in the wallet associated with that instance (or would it be okay to lose that wallet)?

**Comment by tzarebczan** [comment]
Also, how much memory is available on the server? LBRYcrd requires around 4GB to run currently.

**Comment by osiztechnologies** [comment]
What version were you running before?   -   12.2.0
What OS are you on? - ubuntu 16.04
You're using an official build or you compiled it yourself?  - lbrycrd-linux.zip - v0.12.4.1
What block number failed? - above 450000

**Comment by osiztechnologies** [comment]
@tzarebczan 

we have used 16GB of memory in instance.
Kindly share how to clear the data/banned list from the wallet.

**Comment by tzarebczan** [comment]
Yes, sounds like you were on the old chain and need to clear out. The link I shared before has this information. You pretty much want to clear out everything in the lbrycrd folder **except for your wallet, and configuration file**.

**Comment by BrannonKing** [comment]
0.12.4.0 contained a hard-fork that went live at the end of March. That means you've been on the wrong chain for two months. Sure it was failing on 450000 rather than 540000 ?

**Comment by osiztechnologies** [comment]
@tzarebczan we have tried. but same issue occurred again.

**Comment by BrannonKing** [comment]
We don't have enough information to solve this at the moment. I need some log files. Can you upload them somewhere and put a link here?

**Comment by osiztechnologies** [comment]
Hereby i have attached debug.log file for your reference. 
[debug.log](https://github.com/lbryio/lbrycrd/files/3215811/debug.log)

**Comment by BrannonKing** [comment]
Thanks for the log file. Here's what I get from the log file: the last time that your older version was ran it wasn't clean killed. I.e. it was killed with SIGKILL rather than SIGTERM or SIGINT. Hence, the database was not in a clean state, it was probably corrupted. After that, I see many attempts to run that all crash in a similar manner. It's possible that they are crashing on corrupt data in the database. However, it's more likely that the OS is terminating them for too much RAM usage or you're out of disk space.

**Comment by osiztechnologies** [comment]
@BrannonKing Kindly share how to overcome this issue.

**Comment by tzarebczan** [comment]
@osiztechnologies have you followed the directions above (https://github.com/lbryio/lbrycrd/issues/278#issuecomment-494837854) or on https://lbry.com/news/hf1903 ? 

Shoot me a DM on chat.lbry.com (@jiggytom) if you need help with this process. Closing the issue for now as it seems to be upgrade related.
