### ISSUE TITLE
support GCC 8.3 or document that 6 should be used

### ISSUE THREAD

**Issue by shyba** [lbryio/lbrycrd#282]
tried and bdb build fails. GCC 6 works
error output is huge, but this is repeated all over the place:
```
../dist/../dbinc/atomic.h:179:19: error: definition of ‘int __atomic_compare_exchange(db_atomic_t*, atomic_value_t, atomic_value_t)’ ambiguates built-in declaration ‘bool __atomic_compare_exchange(long unsigned int, volatile void*, void*, void*, int, int)’
static inline int __atomic_compare_exchange(
                  ^~~~~~~~~~~~~~~~~~~~~~~~~
make: *** [Makefile:2020: cxx_dbc.o] Error 1
```

**Comment by lbrynaut** [comment]
Thanks @shyba .  The reported issue is specifically for building dependencies, via reproducible build.  A known work-around is to run the script as: `CC=gcc-6 CXX=g++-6 ./reproducible_build.sh`

**Comment by BrannonKing** [comment]
Saving link: https://patchwork.ozlabs.org/patch/932375/

**Comment by BrannonKing** [comment]
Yesterday I realized that the "depends" build had this fixed ages ago (in upstream bitcoin which we recently merged). @shyba tested it also and saw no problems.

**Comment by BrannonKing** [comment]
in master now. (use build.sh or packaging/build_*)
