### ISSUE TITLE
expiration fork isn't set in miner.cpp

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lbrycrd#287]
The fork expiration isn't set in miner.cpp. This causes a failure when testing mining on regtest (when mining past the expiration fork -- use the fuzz test). This is because the mined block doesn't have the same expiration time that the block validation uses.

I'd like to see us remove the expiration time state from claimtrie and claimtriecache. It should check the expiration height computation in overloaded methods like we do for normalization. This won't be any worse performance because we do the check in validation.cpp on every increment/decrement anyhow.

**Comment by bvbfan** [comment]
#296
