### ISSUE TITLE
Put -getinfo on API

### ISSUE THREAD

**Issue by danger89** [lbryio/lbrycrd#304]
Currently the only way of getting information about the node is running the following command on the command-line:

`lbrycrd-cli -getinfo`

Please, also provide a JSON RPC interface, for example with `getinfo` method:

```sh
curl --user myusername --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "getinfo", "params": [] }' -H 'content-type: text/plain;' http://127.0.0.1:9245/
```
Regards,
Melroy

**Comment by eggplantbren** [comment]
I think `getinfo` only exists on old versions of `lbrycrdd` and has been replaced with other things. Apart from that I'll let someone else answer the rest of the issue.

**Comment by danger89** [comment]
You are right. Let's just use: `getblockchaininfo` & `getnetworkinfo` methods.
