### ISSUE TITLE
check dustrelayfee and how this affects vouts

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrycrd#307]
We are having an issue with small vout transactions not being accepted, even though the fees are higher than the dustrelayfee, the client still treats it as dust.

**Comment by BrannonKing** [comment]
The current plan is to move this from 3000 to 1000 sats in the next release. We think that 1000 sats was the default in the v12 releases, but it may not have always been enforced the exact same way.

**Comment by BrannonKing** [comment]
merged via #317
