### ISSUE TITLE
Improve behavior when killing process abruptly / machine dying

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrycrd#309]
Today, if you kill lbrycrd without using the stop command or if the machine crashes, you'll get an error about reindexing and reindexing chainstate. Per @BrannonKing , reindex-chainstate may not work well in all instances and should be avoided.

We should also somehow store the state better so it's able to recover from these types of crashes.

**Comment by BrannonKing** [comment]
Merged via https://github.com/lbryio/lbrycrd/pull/308
