### ISSUE TITLE
releases before v17 showed CLAIM_NAME in ASM instead of OP_NOP6

### ISSUE THREAD

**Issue by BrannonKing** [lbryio/lbrycrd#311]
v17 upstream added script_tests, which tests break when changing this. I verified that the old code did indeed modify the strings in script.cpp. See 
![image](https://user-images.githubusercontent.com/1509322/64377424-a68a7e80-cfe7-11e9-891c-ba5c2e5e3eae.png)

**Comment by bvbfan** [comment]
#314

**Comment by BrannonKing** [comment]
Merged via #314
