### ISSUE TITLE
Performance issues with large wallets

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbrycrd#374]
(Not going to try cause like 6 people understand better than me)

**Comment by kauffj** [comment]
Blocking https://github.com/lbryio/internal-apis/issues/1176

**Comment by BrannonKing** [comment]
The wallet performance regression was fixed in the v0.17.4.4 release. The other wallet performance issues stem from the inherited bitcoin mess-of-a-wallet. I recommend that you batch your high-frequency sends and utilize the sendmany RPC call once every five seconds.
