### ISSUE TITLE
Build fails > txdb.cpp:20:10: fatal error: boost/thread/interruption.hpp: No such file or directory

### ISSUE THREAD

**Issue by ma7555** [lbryio/lbrycrd#384]
```
txdb.cpp:20:10: fatal error: boost/thread/interruption.hpp: No such file or directory
 #include <boost/thread/interruption.hpp>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
Makefile:7128: recipe for target 'libbitcoin_server_a-txdb.o' failed
```
How to fix?

**Comment by tzarebczan** [comment]
Sorry to hear about the trouble. Which is are you on? Have you followed https://github.com/lbryio/lbrycrd/blob/v19_master/README.md#running-from-source

Probably easier to run the latest binary: https://github.com/lbryio/lbrycrd/releases/tag/v0.17.3.2

If building from source, this is the last release tag: https://github.com/lbryio/lbrycrd/tree/v0.17.3.2

**Comment by BrannonKing** [comment]
The boost thread library is required. You can use build.sh to automatically download it or install a not-too-old version of boost-dev on your local system.

**Comment by ma7555** [comment]
okay, thanks will install it.
