### ISSUE TITLE
Dead link on the readme

### ISSUE THREAD

**Issue by bitcoinbrisbane** [lbryio/lbrycrd#388]
On the readme, the link "The CLI help is also browsable online at https://lbry.tech/api/blockchain" to https://lbry.tech/api/blockchain is a dead link.

**Comment by tzarebczan** [comment]
Thanks for opening the issue! We'll get this looked at.

**Comment by BrannonKing** [comment]
It's not obvious where the problem is. While you're waiting for a fix, you can get the same information from the command line client. Run `lbrycrd-cli help` to see the list of commands. Then run `lbrycrd-cli help <command>` to see the help for each specific command.

**Comment by bitcoinbrisbane** [comment]
@BrannonKing LN63
![Screenshot from 2020-04-24 09-17-29](https://user-images.githubusercontent.com/8411406/80158760-a5f13780-860c-11ea-8e2c-6fdcaabe48e3.png)

**Comment by BrannonKing** [comment]
Fixed with the re-introduction of the master branch.
