### ISSUE TITLE
fix database flushing issue related to parallel read access to leveldb/sqlite

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbrycrd#395]

**Comment by kauffj** [comment]
idea / hope was that we could force flushing to happen when writes happen (or more frequently)

**Comment by shyba** [comment]
From my post on Slack:

Using @bvbfan branch [block_info_fix](https://github.com/lbryio/lbrycrd/tree/block_info_fix):
```
sqlite> select hex(hash),status from block_info where height =849954;
8B59A67722E7038A944AE1AC81F26E8D82991ECF09FB51C4A0F4BD2271EFA281|189
48F6E69D8CC8D50B1264F321E4E1190142E68A81D979B01457CA409E0F52783F|157
```
Instead of 2 blocks with flag 157 we get the correct one at 157 and the forked at 189
