### ISSUE TITLE
Feature Request: sendfromaddress command that keeps change in original address

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbrycrd#40]
**Edit: If working on this issue, please see [PR#82](https://github.com/lbryio/lbrycrd/pull/82) and either use this as a starting place or at least see the comments.**

I'd like a way to send credits from a specific address and keep the change in that address. Jack and I talked about calling it `sendfromaddress`. I'm not in love with that name (there are already several sendfrom/sendto commands) but I can't thin of a better name. This would be really helpful for maintaining public addresses that have a specific purpose.

Example:
- Address `bFromAddress123` has 5 LBC. Address `bRecipeintAddress456` is empty.
- I run `./lbrycrd-cli sendfromaddress bFromAddress123 bRecipientAddress456 2.3`
- Now `bRecipientAddress456` has 2.3LBC and `bFromAddress123` has 2.6999575LBC (or whatever `2.7 - txn fee` is).

**Comment by lyoshenka** [comment]
@jimmykiselak @kaykurokawa let me know how long you think this would take

**Comment by kaykurokawa** [comment]
Not sure I understand why you really need this? Can you describe why you don't want the change to go into a change address?

**Comment by kimihiro64** [comment]
The goal is so that a particular address can be given a long-standing purpose (also helps with accounting). Like, large wallet has many addresses, but this address will be used for certain spends (bounties for example) whereas another address will be used for a different category of spend (referrals for example).

**Comment by lyoshenka** [comment]
The main purpose is transparency/accounting. Here are several use cases:

- We have a few wallets [here](https://explorer.lbry.io/richlist) labeled "LBRY Hot Wallet". Every time we spend from those hot wallets, hot wallet address changes. You can already see that the fifth wallet (Jack's hot wallet) is not labeled because he spent from it at some point. If we could easily send change back to the original address, we wouldn't have to keep relabeling.

- We would like to have a "bounty address" where credits are allocated to be paid out for bounties. Every time we pay out a bounty, if the change is sent to a change address, the "bounty address" would change. So we can't announce something like "watch this address for bounty-related transactions".

I understand why a change address is usually good - privacy and potential security benefits. In this case, we want the opposite of privacy. We want people to know what the credits are earmarked for and how much we paid out to whom. As for not revealing the public key, I don't think that's a serious concern yet (if you think it should be, I'm all ears).

**Comment by kaykurokawa** [comment]
So it sounds like you need a user interface to do this so you can just use coin control through the GUI  , (Go to settings->Wallet-> and check enable coin control ). This will give you an interface when sending coins to specify your change address. I thin this should be sufficient for your need unless you really need an RPC command ( On the RPC side, you could use the command createrawtransaction, signrawtransaction, and sendrawtransaction which will accomplish what you need, but is not fool proof)

**Comment by lyoshenka** [comment]
The GUI is only for lbryum. I'd like this in lbrycrd as well. I don't *need* it, its more of a nice-to-have. I have used raw transactions in the past but it's annoying and I'm constantly scared I'll mess something up.

**Comment by lyoshenka** [comment]
And actually, it would be nice as an RPC command for things like the invites wallet (which uses lbrycrd RPC).

**Comment by jackrobison** [comment]
In lbryum there's a -F flag for the from address and -c for a change address. I think something like that would be preferable to a dedicated sendfromaddress command.

**Comment by lyoshenka** [comment]
I agree, but that would be totally inconsistent with the way lbrycrd-cli works.

**Comment by kaykurokawa** [comment]
@lyoshenka, there is a GUI for lbrycrd, it'll be compiled under the /src/qt folder 

I don't want to change how old rpc commands work, but I can either make a new command, or perhaps create a python script that utilizes the rpc commands and do what you want. I'm leaning towards the python script because it'll be easier.

**Comment by lyoshenka** [comment]
I'd prefer it as an RPC command so its easy for other scripts to interact with it. But if its significantly longer to do it that way, I'll take a python script.

**Comment by lyoshenka** [comment]
Actually, I have a python script that does it (wrote it a while ago, thought I lost it). Still would prefer it in lbrycrd.

This is not really a priority. Maybe we can ask someone else to do this for us?

**Comment by kaykurokawa** [comment]
could be a good bounty thing

**Comment by OppenheimerAndTheMartians** [comment]
Hello,

I'm new to LBRY and trying to find some way I can contribute. I can't say I have a lot of experience with blockchain tech, but I do have some with C++. Are you still looking for someone to enhance this feature?

**Comment by lyoshenka** [comment]
Yea, go for it. If you can understand c++ well, I think this shouldn't be too hard. You can take a look at how `sendtoaddress` works - that's where I started. If you get stuck, we'll do our best to help.

Also , it doesn't have to be called `sendfromaddress`. I'm open to a better name.

**Comment by OppenheimerAndTheMartians** [comment]
Where in the code is it? I'm sorry, I'm still figuring everything out.

**Comment by lyoshenka** [comment]
I would start with
https://github.com/lbryio/lbrycrd/blob/774246d16f0d6de2e02c2e319f316953a17f6764/src/wallet/rpcwallet.cpp#L955

**Comment by OppenheimerAndTheMartians** [comment]
I've begun working on the pseudocode for this. Sorry it took me a couple of days, I'm still getting set in my routines on my end... 

How does transfercredit or transferfromaddress sound as a name, BTW?

**Comment by lyoshenka** [comment]
transferfromaddress is not bad. That sort of implies that the change is
staying in the original address

**Comment by lyoshenka** [comment]
Sounds like nothing's happening here. Closing.

**Comment by lyoshenka** [comment]
Reopening and tagging help-wanted.

**Comment by alyssaoc** [comment]
@lyoshenka Is this issue still valid? Does it need to be modified for the new wallet?
