### ISSUE TITLE
micro blogging mastodon compatible ActivityPub protocol feature request

### ISSUE THREAD

**Issue by TwoTwenty** [lbryio/lbrycrd#411]
Sorry if I have submitted this to the wrong spot I was not sure where to make a feature request. 

I was talking with someone in the live chat of a RT live stream on odysee today.  

The other user of odysee mentioned that he would like to have a single identity store to access all things social and federated like LBRY/Odysee is vs youtube.  

we have a fragmentation of social networks like twitter facebook etc... Mastodon and activity pub compatible micro blogging networks already have a massive amoutn of users and federated servers. if odysee joined this federation in a time that its booming could really help unite the world again in a way we can all trust. 

If people could access odysee and it also made up a microblogging system that would be next level 

Please consider this feature request.

**Comment by BrannonKing** [comment]
This is definitely the wrong spot to post. Try one of the repositories here: https://github.com/OdyseeTeam . Maybe they can direct you to the right spot from there.
