### ISSUE TITLE
OSX Not using HyperThreading

### ISSUE THREAD

**Issue by juanpc2018** [lbryio/lbrycrd#415]
HighSierra 10.13.6
Activity Monitor shows "half the cores"

There is a Software to disable HT in OSX to avoid using Xcode.
https://whatroute.net/cpusetter.html#download

Reducing cores makes CPU faster because TurboBoost v1 in Westmere and Nehalem,
Newer intel machines have TurboBoost v2
MacPro 7,1 2019, maybe Macmini 2018, MBP 2019

Not a Big Deal.

Linux has HT,
same machine. MP5,1 2010

the equivalent in Windows is msconfig

**Comment by BrannonKing** [comment]
Are you talking about the compilation of lbrycrd? From the description above, I cannot tell what bug you are reporting nor what you are requesting gets fixed.

**Comment by BrannonKing** [comment]
Closed due to no response and insufficient information.
