### ISSUE TITLE
lbrycrd-cli Info still says "BTC"

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#42]
from @theunrealtok

error message:
getwalletinfo
Returns an object containing various wallet state info.

Result:
{
"walletversion": xxxxx, (numeric) the wallet version
"balance": xxxxxxx, (numeric) the total confirmed balance of the wallet in BTC
"unconfirmed_balance": xxx, (numeric) the total unconfirmed balance of the wallet in BTC
"immature_balance": xxxxxx, (numeric) the total immature balance of the wallet in BTC
"txcount": xxxxxxx, (numeric) the total number of transactions in the wallet
"keypoololdest": xxxxxx, (numeric) the timestamp (seconds since GMT epoch) of the oldest pre-generated key in the key pool
"keypoolsize": xxxx, (numeric) how many new keys are pre-generated
"unlocked_until": ttt, (numeric) the timestamp in seconds since epoch (midnight Jan 1 1970 GMT) that the wallet is unlocked for transfers, or 0 if the wallet is locked
"paytxfee": x.xxxx, (numeric) the transaction fee configuration, set in BTC/kB
}

**Comment by r3c0d3x** [comment]
In [src/amount.cpp, line 10](https://github.com/lbryio/lbrycrd/blob/5913a70f7ee3bb20cc663b01259af8b1f3c37999/src/amount.cpp#L10):
```cpp
const std::string CURRENCY_UNIT = "BTC";
```

**Comment by lyoshenka** [comment]
Fixed by #61
