### ISSUE TITLE
aborted on ubuntu 14.04

### ISSUE THREAD

**Issue by janellebradleyZ8p** [lbryio/lbrycrd#57]
lbrycrdd: main.cpp:2387: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, CClaimTrieCache&, bool): Assertion `hashPrevBlock == trieCache.getBestBlock()' failed.

Tried binaries and now I also got same error even when compiled myself.

**Comment by kaykurokawa** [comment]
did you try compiling from the current master?

**Comment by janellebradleyZ8p** [comment]
Yes I did, the error above appeard only when I started daemon with conf file.

I run it now with on in command line.
