### ISSUE TITLE
dumpprivkey returning a 52-character base58 string starting with '5'

### ISSUE THREAD

**Issue by akinwale** [lbryio/lbrycrd#63]
Based on https://en.bitcoin.it/wiki/Private_key#Base58_Wallet_Import_format, The Wallet Import Format key is expected to be a 51-character base58 string, but dumpprivkey is returning a 52-character string which cannot be properly converted to a base58 address based on the public key.

Just for reference, https://en.bitcoin.it/wiki/Wallet_import_format shows steps for converting a private key to/from base58.

Here's an example I tested with:
```
ubuntu@lbry:~# curl -X POST -d '{"method": "getnewaddress", "params": []}' http://rpc:rpc@127.0.0.1:9245
{"result":"bGdQJgLwXSZ6eajyjgvqz9aMZ2RqkNbD1y","error":null,"id":null}
ubuntu@lbry:~# curl -X POST -d '{"method": "dumpprivkey", "params": ["bGdQJgLwXSZ6eajyjgvqz9aMZ2RqkNbD1y"]}' http://rpc:rpc@127.0.0.1:9245
{"result":"5GBWLGQu5NiaCNLzTtLMTGMVfAkmB6pBqFt9nYvpNXcGxsqCWY3h","error":null,"id":null}
```
I have release v0.12.0.4 installed on both Ubuntu and Windows 10. Here's my getinfo output.
```
{"result":{"version":129900,"protocolversion":70013,"walletversion":60000,"balance":0.00000000,"blocks":190158,"timeoffset":0,"connections":12,"proxy":"","difficulty":190641.6861993672,"testnet":false,"keypoololdest":1497023671,"keypoolsize":101,"paytxfee":0.00000000,"relayfee":0.00001000,"errors":"This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"},"error":null,"id":null}
```

**Comment by kaykurokawa** [comment]
if the private key is compressed it has 52 characters :
https://bitcoin.org/en/developer-guide#wallet-import-format-wif

see step 3: 
Append a 0x01 byte after it if it should be used with compressed public keys (described in a later subsection). Nothing is appended if it is used with uncompressed public keys.

**Comment by akinwale** [comment]
This doesn't change the fact that the dumped private key is invalid, though. The base58 strings for compressed keys are expected to start with a 'K' or an 'L'.

Another tool you can use to test dumped private keys is bitaddress.org.
