### ISSUE TITLE
2 pools (yiimp based) reporting Rejects / claimtrie issues?

### ISSUE THREAD

**Issue by kauffj** [lbryio/lbrycrd#66]
_From @tzarebczan on July 24, 2017 16:23_

So we are getting reports from a couple pools about rejects leading to them not finding blocks. Something about our claimtrie. However the large suprnova pool seems to deal with it.

reject and debug logs from @reymus pool (quantumrage) - using same yiimp implementation as Epsylon. http://quantumrage.com/files/errorlogs.tar.gz

BCT Thread where he mentioned the claimtrie issue:
https://bitcointalk.org/index.php?topic=770064.msg20328909#msg20328909

@finer9 - can you reach out to Epsylon for his logs - could help potentially. 

_Copied from original issue: lbryio/internal-issues#11_

**Comment by finer9** [comment]
So we've been basically removed from YIMP due to this.  They were never a huge pool but are quality and I wish we could figure this out.

**Comment by finer9** [comment]
If I recall epsylon is on github and perhaps we can tag him

**Comment by tpruvot** [comment]
I dont have the logs anymore, last reject was the 20 july and i had to restart the machine the 21 or 22

**Comment by finer9** [comment]
ah thanks for replying.  Do you have any idea how pools like suprnova handle this?  Do you think we need changes to our claimtrie?

**Comment by tpruvot** [comment]
i guess he get more blocks, so dont care about the % of rejects, will ask him

**Comment by finer9** [comment]
@kaykurokawa appreciate you looking at this when possible

**Comment by tpruvot** [comment]
but the reject reason was always the same... claimtrie not updated fast enough...

**Comment by kaykurokawa** [comment]
I belelive this should be fixed now https://github.com/lbryio/lbrycrd/pull/70

**Comment by tpruvot** [comment]
Thanks, re-enabled it on yiimp for same-config tests :) but looks good, indeed.

**Comment by aayanl** [comment]
![](https://user-images.githubusercontent.com/10069649/30508588-5d59434c-9a68-11e7-86fc-28ae59ac383e.gif)

**Comment by tzarebczan** [comment]
Closing, fixed by https://github.com/lbryio/lbrycrd/pull/70
