### ISSUE TITLE
Custom crypto = scary scary

### ISSUE THREAD

**Issue by ikeydoherty** [lbryio/lbrycrd#69]
I know this is inherited from the BTC fork, however I'd like to point out the obvious issue of having custom crypto code. It's basically rule #1 of any project, never reinvent crypto. Looking at the basic crypto requirements in lbrycrd it seems this could more easily be resolved with OpenSSL, gnutls, etc (Given that the requirement effectively seems to be hash/hmac centric)

Soo would you consider nuking or allowing external hash lib providers (`configure.ac` options?)

**Comment by lyoshenka** [comment]
Has bitcoin changed anything here? I'm aware of the dangers of rolling your own crypto. At the same time, bitcoin has far more developers and cryptographers looking at their code. If they're still using the same crypto, I'd rather not mess with it.
