### ISSUE TITLE
"This is a pre-release test build...."

### ISSUE THREAD

**Issue by tzarebczan** [lbryio/lbrycrd#71]
Seeing this in lbrycrd-cli getinfo on latest build from master:

"This is a pre-release test build - use at your own risk - do not use for mining or merchant applications"

I think it may need a version bump somewhere.

**Comment by filipnyquist** [comment]
This should be quite simple to solve and should be added asap as otherwise people might think that it´s not safe to use.

**Comment by oakey22** [comment]
Can this be done soon please?

**Comment by lyoshenka** [comment]
@kaykurokawa can you do this when you're working on lbrycrd next?

**Comment by filipnyquist** [comment]
https://github.com/lbryio/lbrycrd/blob/270307a29070a4c10095528e232ad0f8e251ec5a/doc/release-process.md contains info on how to build a full releasem without the warnings
