### ISSUE TITLE
Lbrycrd claimtrie unit test improvements 

### ISSUE THREAD

**Issue by kaykurokawa** [lbryio/lbrycrd#83]
Old tests for the claimtrie ( https://github.com/lbryio/lbrycrd/blob/master/src/test/claimtrie_tests.cpp ) should be merged with new tests which contains fixtures and functions to make the expansion of unit tests easier: https://github.com/lbryio/lbrycrd/blob/master/src/test/claimtriebranching_tests.cpp

The new tests could also be improved more, it is mainly testing for the best claim, and we should test other things in the claim trie such as the number of claims in the trie, check if the claimtrie root merkle hash is being updated, check that supports are present in the claim trie directly, etc..

**Comment by BrannonKing** [comment]
done via #183
