### ISSUE TITLE
Update Bitcoin codebase to support Atomic Swaps/decentralized OTC exchange

### ISSUE THREAD

**Issue by real-rouse** [lbryio/lbrycrd#86]
In the time when centralized exchanges are on the fall, in fear of strict regulation - It is time to enable support for decentralized and trustless on-chain and off-chain OTC (over-the-counter) exchanges between cryptocurrencies. By updating the codebase of LBRY to the newest codebase of Bitcoin, we will be able to support Atomic Swaps. 
https://github.com/decred/atomicswap
Decred (https://Decred.org) made a repository here. We can fork it.

Here is a picture made by Particl, illustrating how it works: https://image.ibb.co/jcomwm/atomic_swap.png

I will also write about these issues at https://LBRY.Community

**Comment by real-rouse** [comment]
I am open for discussion on this matter.

**Comment by alyssaoc** [comment]
this will happen when upstream issues are merged

**Comment by lyoshenka** [comment]
tracking upstream merge progress in #174
