### ISSUE TITLE
Update Bitcoin codebase to support Lightning network to solve scalability issues

### ISSUE THREAD

**Issue by real-rouse** [lbryio/lbrycrd#87]
I think this could be relevant to make LBRY scale up for millions of users. I believe it is soon time for LBRY to hardfork!

I will also write about these issues at https://LBRY.Community

**Comment by real-rouse** [comment]
I am open for discussion on this matter. :)

**Comment by BrannonKing** [comment]
@real-rouse , where is your write-up on Lightning? Have a direct link?

**Comment by alyssaoc** [comment]
compatibility will be solved with the merger to current bitcoin codebase

**Comment by lyoshenka** [comment]
tracking upstream merge progress in #174

**Comment by real-rouse** [comment]
Sorry @BrannonKing  , I haven't written about it yet. I have been busy with some other things. This issue is still in the back of my head, and I will probably write more about it when the LBRY blockchain is actually getting more unconfirmed transactions, and when the lightning network is developed more. Here is a link to https://lightning.network if you're interested btw. :)
