### ISSUE TITLE
memory usage 1

### ISSUE THREAD

**Issue by lyoshenka** [lbryio/lbrycrd#88]
Do preliminary work in checking places where the claimtrie uses memory, verify that the empty nodes are the main problem, check if there is some quick optimization that will improve memory usage.

After this is done, create new issues in this epic for the rest of the work.

**Comment by kaykurokawa** [comment]
closing this in favor of new issues : 
https://github.com/lbryio/lbrycrd/issues/90
https://github.com/lbryio/internal-issues/issues/117
