### ISSUE TITLE
Supports returned for a claim should include the address the support was sent to

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbrycrd#92]
Currently the txid, nout, and amount of the support is returned. By including address, clients can determine if a support is a "tip" (a support sending to the address of the claim) versus a typical support. Otherwise if addresses are desired all of the support transactions in the list have to be queried and parsed.

**Comment by tzarebczan** [comment]
@kaykurokawa when would that happen? Can that support never be spent? Or would it go back to the sending address?

**Comment by kaykurokawa** [comment]
Claims can be attached to any kind of Bitcoin transaction. 
Bitcoin transactions do not necessarily have an address attached to it (i.e., some kind of un-spendable transaction )

**Comment by BrannonKing** [comment]
Merged via https://github.com/lbryio/lbrycrd/pull/303
