### ISSUE TITLE
Improving lbrycrd binary install

### ISSUE THREAD

**Issue by lbrydocs** [lbryio/lbrycrd#93]
I am working on documentation for installs of the main pieces of the LBRY system. I use the following environment for testing:

Lubuntu 16.04.3 LTS - Ubuntu derived, takes half the disk space due to graphics diet.
apt update/apt upgrade so it's current.
tmux - share screens and log activity to text file, so I can watch a developer do an install.

When I download and unzip the lbrycrd binaries for Linux that part works fine, but there is no README to explain what to do, no example config, and no lbrycrdd.service file for systemd.

This is what we did for the daemon's configuration:

> cat >  ~/.lbrycrd/lbrycrd.conf
> port=9246
> bind=127.0.0.1
> 
> rpcallowip=127.0.0.1
> rpcbind=127.0.0.1
> rpcport=9245
> rpcuser=lbryrpc
> rpcpassword=securepassw0rd
> 
> server=1
> txindex=1
> ctrl-d

And I didn't record the contents of /etc/systemd/system/lbrycrdd.service and I've since recycled the VPS where we did that, so I do not have a copy of that text handy.

**Comment by BrannonKing** [comment]
To be clear, this is a request for DEB packaging for Linux deployment? And we should host those on our own PPA somewhere? Would Snap packaging be okay (instead of DEB)?

**Comment by tzarebczan** [comment]
The readme was recently updated to include a config example and how to run lbrycrdd. I think that might be enough to close this issue.

**Comment by alyssaoc** [comment]
closed per Tom's comment
