### ISSUE TITLE
Rejected dust transactions return error code 64 instead of 65

### ISSUE THREAD

**Issue by jackrobison** [lbryio/lbrycrd#97]
The constant `REJECT_DUST` is [never used](https://github.com/lbryio/lbrycrd/blob/fa24439ff3d8ab5b9efaf66ef4dae6713b88cb35/src/consensus/validation.h#L17).

I think this is where the incorrect error code is coming from: https://github.com/lbryio/lbrycrd/blob/51d6b690cb2adae1dfa8bc042a07e476ea7edf15/src/main.cpp#L1037

The above calls: https://github.com/lbryio/lbrycrd/blob/e08d765f11a421d0b832ecefcc859c5598fa56d0/src/policy/policy.cpp#L109

**Comment by kaykurokawa** [comment]
looks like REJECT_NONSTANDARD is a catchall error type for the IsStandardTx function , and it would be better if it was refined to return the more specific error codes such as REJECT_DUST

**Comment by bvbfan** [comment]
https://github.com/lbryio/lbrycrd/pull/185
